import Foundation

/// Represents a candidate replacement word generated by the Smart Correction Engine.
public struct CorrectionCandidate: Sendable, Equatable, Hashable {
    public let word: String
    public var confidence: Double
    public let editDistance: Int
    public let sourceStage: String

    public init(word: String, confidence: Double, editDistance: Int, sourceStage: String) {
        self.word = word
        self.confidence = confidence
        self.editDistance = editDistance
        self.sourceStage = sourceStage
    }
}

/// Protocol defining a modular stage inside the correction pipeline.
/// Extensible to support future modules such as Grammar, AI completion, Multilingual, or LLM-powered correction.
public protocol CorrectionStage: Sendable {
    var stageName: String { get }
    func process(input: String, contextBefore: [String], currentCandidates: [CorrectionCandidate], engine: SmartCorrectionEngine) -> [CorrectionCandidate]
}

/// The core 5-Stage Smart Correction Engine orchestrator.
public final class SmartCorrectionEngine: @unchecked Sendable {
    public let database: SQLiteDatabase
    public let dictionaries: BuiltinDictionaries
    public let keyboardModel: KeyboardModel
    public let symSpell: SymSpellEngine
    public let bkTree: BKTreeEngine
    private let lock = NSLock()
    
    public private(set) var stages: [CorrectionStage] = []
    private var isIndexed = false

    public init(database: SQLiteDatabase, dictionaries: BuiltinDictionaries, keyboardModel: KeyboardModel = KeyboardModel()) {
        self.database = database
        self.dictionaries = dictionaries
        self.keyboardModel = keyboardModel
        self.symSpell = SymSpellEngine(maxEditDistance: 2)
        self.bkTree = BKTreeEngine()

        // Register default 5 stages in order of priority
        self.stages = [
            ExactLookupStage(),
            SymSpellStage(),
            BKTreeStage(),
            RapidRankingStage(),
            ContextValidationStage()
        ]
    }

    /// Allows dynamically registering additional modules (e.g., GrammarCorrectionStage or LLMCorrectionStage).
    public func registerStage(_ stage: CorrectionStage) {
        lock.lock()
        stages.append(stage)
        lock.unlock()
    }

    /// Pre-indexes dictionary words into SymSpell and BK-Tree for sub-millisecond query execution.
    public func prepareIndexIfNeeded() {
        lock.lock()
        if isIndexed {
            lock.unlock()
            return
        }
        lock.unlock()

        try? dictionaries.seedDefaultDictionariesIfNeeded()
        let words = dictionaries.allCachedWords()
        symSpell.indexWords(words)
        bkTree.insertBatch(words)

        lock.lock()
        isIndexed = true
        lock.unlock()
    }

    /// Indexes a single newly added word into memory indexes.
    public func indexNewWord(_ word: String) {
        symSpell.indexWord(word)
        bkTree.insert(word)
    }

    /// Preserves uppercase or title case from original input, auto-capitalizes at line/sentence starts, and capitalizes standalone pronoun 'i'.
    public static func preserveCase(candidate: String, originalInput: String, isStartOfSentenceOrLine: Bool = false) -> String {
        guard !candidate.isEmpty else { return candidate }
        
        // 0. Single letter 'i' pronoun in English should always be capitalized 'I' when standalone
        if candidate.lowercased() == "i" && candidate.count == 1 {
            return "I"
        }

        let originalLetters = originalInput.filter { $0.isLetter }
        // 1. All Uppercase check: if original had at least 2 letters and all cased characters were uppercase ("TEH", "RECIEVE", "APLE")
        if originalLetters.count > 1 && originalLetters.allSatisfy({ $0.isUppercase }) {
            return candidate.uppercased()
        }
        
        // 2. Title case check or Auto-capitalization check:
        // If the original input started with a capital letter ("Teh", "Recieve"), or if we are at start of sentence/line
        let firstLetterIsUpper = originalInput.first?.isUppercase == true
        if firstLetterIsUpper || isStartOfSentenceOrLine {
            var chars = Array(candidate)
            if let first = chars.first {
                chars[0] = Character(String(first).uppercased())
                return String(chars)
            }
        }
        
        return candidate
    }

    /// Main correction evaluation entrypoint ($O(1)$ or sub-5ms latency).
    /// Evaluates input word through all registered correction stages and returns the best candidate if its confidence exceeds threshold.
    public func evaluate(word: String, contextBefore: [String] = [], threshold: Double = 0.95, isStartOfSentenceOrLine: Bool = false, externalCandidates: [String] = []) -> CorrectionCandidate? {
        prepareIndexIfNeeded()
        let cleanWord = word.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanWord.isEmpty else { return nil }

        // Check if word is explicitly ignored or set to always replace
        if let rule = database.getIgnoreRule(for: cleanWord) {
            switch rule.type {
            case .alwaysReplace:
                if let repl = rule.replacement, !repl.isEmpty {
                    let formatted = SmartCorrectionEngine.preserveCase(candidate: repl, originalInput: cleanWord, isStartOfSentenceOrLine: isStartOfSentenceOrLine)
                    return CorrectionCandidate(word: formatted, confidence: 1.0, editDistance: 0, sourceStage: "IgnoreRule")
                }
            case .neverSuggest, .once, .forever:
                return nil
            }
        }

        // Seed candidates from system spellchecker guesses or other caller-provided sources.
        var candidates = externalCandidatesForRanking(externalCandidates, input: cleanWord)
        for stage in stages {
            candidates = stage.process(input: cleanWord, contextBefore: contextBefore, currentCandidates: candidates, engine: self)
            
            // Short-circuit: if exact stage returns a candidate with confidence == 1.0 and 0 edit distance
            if stage.stageName == "Stage1_ExactLookup", let exactMatch = candidates.first(where: { $0.confidence == 1.0 && $0.editDistance == 0 }) {
                let formattedWord = SmartCorrectionEngine.preserveCase(candidate: exactMatch.word, originalInput: cleanWord, isStartOfSentenceOrLine: isStartOfSentenceOrLine)
                if formattedWord != cleanWord {
                    return CorrectionCandidate(word: formattedWord, confidence: 1.0, editDistance: 0, sourceStage: "AutoCapitalization")
                }
                return nil // Exact match in dictionary, case is already correct!
            }
        }

        // Filter and return the top candidate if above threshold
        guard let bestRaw = candidates.max(by: { $0.confidence < $1.confidence }) else {
            return nil
        }
        
        let formattedCandidate = SmartCorrectionEngine.preserveCase(candidate: bestRaw.word, originalInput: cleanWord, isStartOfSentenceOrLine: isStartOfSentenceOrLine)
        let best = CorrectionCandidate(word: formattedCandidate, confidence: bestRaw.confidence, editDistance: bestRaw.editDistance, sourceStage: bestRaw.sourceStage)

        if best.confidence >= threshold && best.word != cleanWord {
            return best
        }
        return nil
    }

    private func externalCandidatesForRanking(_ words: [String], input: String) -> [CorrectionCandidate] {
        var candidates = [CorrectionCandidate]()
        let lowerInput = input.lowercased()
        var seen = Set<String>()

        for word in words {
            let clean = word.trimmingCharacters(in: .whitespacesAndNewlines)
            let lower = clean.lowercased()
            guard !clean.isEmpty, lower != lowerInput, !seen.contains(lower) else { continue }
            seen.insert(lower)

            let distance = SymSpellEngine.damerauLevenshteinDistance(lowerInput, lower)
            candidates.append(
                CorrectionCandidate(
                    word: clean,
                    confidence: 0.82,
                    editDistance: distance,
                    sourceStage: "Stage0_AppleSpell"
                )
            )
        }

        return candidates
    }

    // MARK: - Context / Bigram Helper
    public func contextBoost(for candidateWord: String, givenContext context: [String]) -> Double {
        guard !context.isEmpty else { return 0.0 }
        let lastWord = context.last!.lowercased()
        let target = candidateWord.lowercased()

        // High-confidence contextual bigrams ("in the garabage" -> "garbage")
        let bigramPatterns: [String: Set<String>] = [
            "the": ["garbage", "recommendation", "definition", "address", "occurrence", "accommodate", "government", "friend", "world", "time"],
            "in": ["the", "garbage", "america", "world", "time", "python", "swift"],
            "to": ["recommend", "accommodate", "receive", "write", "learn", "study"],
            "will": ["definitely", "occur", "receive", "accommodate", "recommend", "happen"],
            "is": ["definitely", "apparent", "aggressive", "weird", "truly"],
            "email": ["address"],
            "home": ["address"],
            "an": ["occurrence", "address", "animal", "answer"]
        ]

        if let expectedSet = bigramPatterns[lastWord], expectedSet.contains(target) {
            return 0.15 // 15% confidence boost for matching strong context
        }
        return 0.0
    }
}

// MARK: - Stage 1: Exact Lookup ($O(1)$)
public struct ExactLookupStage: CorrectionStage {
    public let stageName = "Stage1_ExactLookup"

    public func process(input: String, contextBefore: [String], currentCandidates: [CorrectionCandidate], engine: SmartCorrectionEngine) -> [CorrectionCandidate] {
        let lower = input.lowercased()
        
        // First check User Frequency model override (e.g. user typed "Raycast" 5000 times, and currently typed "Raycats")
        if let exempted = KeyboardModel.commonTypoExemptions[lower] {
            // Immediate exemption boost
            let candidate = CorrectionCandidate(word: exempted, confidence: 0.99, editDistance: 1, sourceStage: stageName)
            return [candidate]
        }

        // Check if input exactly exists in built-in dictionaries or user dictionary
        if engine.dictionaries.exactFrequency(for: lower) != nil {
            // Check if there is an overwhelmingly popular user word that is 1 transposition/edit away
            // For O(1) efficiency, if the exact word is valid, we emit it as 1.0 confidence
            return [CorrectionCandidate(word: input, confidence: 1.0, editDistance: 0, sourceStage: stageName)]
        }
        return currentCandidates
    }
}

// MARK: - Stage 2: SymSpell (Edit Distance Candidates)
public struct SymSpellStage: CorrectionStage {
    public let stageName = "Stage2_SymSpell"

    public func process(input: String, contextBefore: [String], currentCandidates: [CorrectionCandidate], engine: SmartCorrectionEngine) -> [CorrectionCandidate] {
        if !currentCandidates.isEmpty && currentCandidates[0].confidence == 1.0 {
            return currentCandidates
        }

        var results = currentCandidates
        let symMatches = engine.symSpell.lookup(input)
        for match in symMatches {
            let dist = SymSpellEngine.damerauLevenshteinDistance(input.lowercased(), match)
            let candidate = CorrectionCandidate(word: match, confidence: 0.70, editDistance: dist, sourceStage: stageName)
            if !results.contains(where: { $0.word == match }) {
                results.append(candidate)
            }
        }
        return results
    }
}

// MARK: - Stage 3: BK-Tree Lookup (Nearest Neighbor Search)
public struct BKTreeStage: CorrectionStage {
    public let stageName = "Stage3_BKTree"

    public func process(input: String, contextBefore: [String], currentCandidates: [CorrectionCandidate], engine: SmartCorrectionEngine) -> [CorrectionCandidate] {
        if !currentCandidates.isEmpty && currentCandidates[0].confidence == 1.0 {
            return currentCandidates
        }

        var results = currentCandidates
        // If SymSpell returned few results, backfill with BK-Tree metric search
        if results.count < 5 {
            let treeMatches = engine.bkTree.search(query: input, maxDistance: 2)
            for (word, dist) in treeMatches {
                if !results.contains(where: { $0.word == word }) {
                    results.append(CorrectionCandidate(word: word, confidence: 0.70, editDistance: dist, sourceStage: stageName))
                }
            }
        }
        return results
    }
}

// MARK: - Stage 4: Rapid Ranking
public struct RapidRankingStage: CorrectionStage {
    public let stageName = "Stage4_RapidRanking"

    public func process(input: String, contextBefore: [String], currentCandidates: [CorrectionCandidate], engine: SmartCorrectionEngine) -> [CorrectionCandidate] {
        if !currentCandidates.isEmpty && currentCandidates[0].confidence == 1.0 {
            return currentCandidates
        }

        let lowerInput = input.lowercased()
        var ranked = [CorrectionCandidate]()

        for var candidate in currentCandidates {
            let target = candidate.word.lowercased()
            
            // 1. Keyboard weighted edit cost (distance & typo exemptions)
            let weightedCost = engine.keyboardModel.weightedEditCost(source: lowerInput, target: target)
            var confidence = max(0.1, 1.0 - (weightedCost * 0.25))

            // 2. Word frequency boost
            let freq = engine.dictionaries.exactFrequency(for: target) ?? 1
            let logFreqBoost = min(0.15, log10(Double(freq + 1)) * 0.03)
            confidence += logFreqBoost

            // 3. Historical user preference boost (e.g. Raycast x5000)
            let userCount = engine.database.getUserFrequencyCount(target)
            if userCount > 0 {
                let userBoost = min(0.20, log10(Double(userCount + 1)) * 0.06)
                confidence += userBoost
            }

            // 4. System spellchecker suggestions are strong evidence once macOS has marked the token wrong.
            if candidate.sourceStage == "Stage0_AppleSpell" {
                confidence += 0.12
            }

            // Cap confidence at 0.99 for non-zero edit distance
            if candidate.editDistance > 0 && confidence > 0.99 {
                confidence = 0.99
            }

            candidate.confidence = confidence
            ranked.append(candidate)
        }

        return ranked.sorted(by: { $0.confidence > $1.confidence })
    }
}

// MARK: - Stage 5: Context Validation
public struct ContextValidationStage: CorrectionStage {
    public let stageName = "Stage5_ContextValidation"

    public func process(input: String, contextBefore: [String], currentCandidates: [CorrectionCandidate], engine: SmartCorrectionEngine) -> [CorrectionCandidate] {
        if !currentCandidates.isEmpty && currentCandidates[0].confidence == 1.0 {
            return currentCandidates
        }

        var validated = [CorrectionCandidate]()
        for var candidate in currentCandidates {
            let boost = engine.contextBoost(for: candidate.word, givenContext: contextBefore)
            candidate.confidence = min(0.99, candidate.confidence + boost)
            validated.append(candidate)
        }

        return validated.sorted(by: { $0.confidence > $1.confidence })
    }
}
